//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyz 
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
vs_4_0
dcl_constantbuffer CB0[4], immediateIndexed
dcl_constantbuffer CB1[32], dynamicIndexed
dcl_constantbuffer CB2[1], immediateIndexed
dcl_input v0.xyz
dcl_input v1.xy
dcl_output_siv o0.xyzw, position
dcl_output o1.xy
dcl_temps 3
mul r0.xyzw, v0.yyyy, cb0[1].xyzw
mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
add r0.xyzw, r0.xyzw, cb0[3].xyzw
ishl r1.x, cb2[0].x, l(2)
mul r2.xyzw, r0.yyyy, cb1[r1.x + 25].xyzw
mad r2.xyzw, cb1[r1.x + 24].xyzw, r0.xxxx, r2.xyzw
mad r2.xyzw, cb1[r1.x + 26].xyzw, r0.zzzz, r2.xyzw
mad o0.xyzw, cb1[r1.x + 27].xyzw, r0.wwww, r2.xyzw
mov o1.xy, v1.xyxx
ret 
// Approximately 0 instruction slots used
