//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// TEXCOORD                 0   xy          1     NONE   float   xy  
// SV_IsFrontFace           0   x           2    FFACE    uint       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_4_0
dcl_constantbuffer CB0[6], immediateIndexed
dcl_constantbuffer CB1[1], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 1
add r0.x, cb0[2].y, cb1[0].y
mad r0.xy, r0.xxxx, cb0[4].xyxx, v1.xyxx
mad r0.xy, r0.xyxx, cb0[3].xyxx, cb0[3].zwzz
sample r0.xyzw, r0.xyxx, t0.xyzw, s0
mul o0.xyz, r0.xyzx, cb0[5].xyzx
mov o0.w, cb0[4].z
ret 
// Approximately 0 instruction slots used
